name: Split CSV Files by Gameweek and Commit
on:
  # Trigger manually from GitHub UI
  workflow_dispatch:

jobs:
  split-csv-files:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas
        
    - name: Run CSV split script
      run: |
        python scripts/split_by_gameweek.py
        
    - name: Configure Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
    - name: Add and commit split files
      run: |
        git add data/2024-2025/matches/GW*/
        git add data/2024-2025/playermatchstats/GW*/
        git commit -m "Add gameweek-split CSV files (GW1-GW38)" || exit 0
        
    - name: Push changes
      run: |
        git push
