name: Split CSV Files by Gameweek (Simple)

on:
  # Trigger manually from GitHub UI
  workflow_dispatch:

jobs:
  split-csv-files:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas
        
    - name: Run CSV split script
      run: |
        python split_by_gameweek.py
        
    - name: Upload split files as artifact
      uses: actions/upload-artifact@v3
      with:
        name: gameweek-split-csvs
        path: data/2024-2025/by_gameweek/
        retention-days: 30
