# .github/workflows/sync.yml
name: Sync CSV Data to Firestore

# This workflow runs on any push to the main branch
on:
  push:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-data:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }} # Paste your provider name here
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }} # Paste your SA email here

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas google-cloud-firestore

      - name: Run the sync script
        run: python sync_to_firestore.py
